# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c661318d0fa5b749d833d984e8d7b61ef53e824f9f69ca62ac28767ecec66e212bb8db96cc7ba9ec5152c638c9aa7e75598adf1fad4806de3ffb845c823b8823

test:
  secret_key_base: 0fcd4dc16dc4a7006e4d3851fc32fede50564c08192c76e1064872585b34d364bf2bdac10e219288f793ebb8b7016ce92b59822ad94ff03b10c2e531255cec6b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
